# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    use_build_context_synchronously: false
    unnecessary_lambdas: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
